- name: installing packages for mail server
  apt:
    pkg:
    - python3-pymysql
    - postfix
    - nginx
    - php-fpm
    - php-mysql
    - php-mbstring
    - php-imap
    - mariadb-server

- include_tasks: mysql_secure_installation.yml
- include_tasks: install_postfixadmin.yml
- include_tasks: install_roundcube.yml
